---
driver:
  #name: docker
  name: vagrant
  use_sudo: false ## MAC HACK

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: dashboard-web
    run_list:
      - recipe[dashboard::apt]
      - recipe[dashboard::nginx]
    attributes:

  - name: dashboard-server
    run_list:
      - recipe[dashboard::apt]
      - recipe[dashboard::ruby]
      - recipe[dashboard::rails]
    attributes:

  - name: dashboard-data
    run_list:
      - recipe[dashboard::apt]
      - recipe[dashboard::mysql]
    attributes:
