---
driver:
  #name: docker
  name: vagrant
  use_sudo: false ## MAC HACK

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: server
    run_list:
      - recipe[mysqld::server]
      - recipe[dashboard::server]
    attributes:    
