---
driver:
  name: docker
  #use_sudo: false ## MAC HACK
  #name: vagrant

provisioner:
  #name: chef_solo
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[git::default]
    attributes:
  - name: server
    run_list:
      - recipe[git::server]
    attributes:    
