---
driver:
  #name: docker
  name: vagrant
  use_sudo: false ## MAC HACK

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: dashboard
    run_list:
      - recipe[dashboard::apt]
      - recipe[dashboard::mysql]
      - recipe[dashboard::git-daemon]
    attributes:    
