# Use this file to configure the Overcommit hooks you wish to use.

PreCommit:
  ALL:
    problem_on_unmodified_line: warn
    requires_files: true
    required: false
    quiet: false

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']
    on_warn: fail # Treat all warnings as failures
    problem_on_unmodified_line: ignore
    include:
      - '**/*.gemspec'
      - '**/*.rb'
      - template-dir/hooks/overcommit-hook

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/structure.sql' # Ignore trailing whitespace in generated files

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

PrePush:
  RSpec:
    enabled: true
